discord_webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN"

channels:
  - id: "UCXuqSBlHAE6Xw-yeJA0Tunw"
    name: "Linus Tech Tips"
  
  - id: "UC9-y-6csu5WGm29I7JiwpnA"
    name: "Computerphile"
  
  - id: "UCsBjURrPoezykLs9EqgamOA"
    name: "Fireship"